### ISSUE TITLE
KISS should preserve folder permissions

### ISSUE THREAD

**Issue by konimex** [kissx/kiss#26]
When bootstrapping `baselayout`, I realized something is wrong with the directories, specifically `/root` and `/tmp`, since their permissions should be `0750` and `1777` but both are `0755`.

Tracking the `pkg_install` process, I found [this](https://github.com/kissx/kiss/blob/52e0940f689c713952cf2da44a28efb0e4286b2f/kiss#L691), perhaps this is the offending command since it creates the directory using default permissions.

**Comment by dylanaraps** [comment]
This should be fixed.

**Comment by a-schaefers** [comment]
i too noticed this
