### ISSUE TITLE
Add flag to 'kiss update' to pull the latest repositories.

### ISSUE THREAD

**Issue by vypr** [kissx/kiss#6]
Not sure if this would go against the philosophy of the manager, but I'm sure that it would be more practical to have a sort of -p/--pull or -s/--sync flag for `kiss update`.

Naturally, this would iterate through all repositories in $KISS_PATH.

The downside is that a git output won't look necessarily pretty, which makes me curious about an alternative progress bar or something that would make it nicer in terms of UI.

Just a thought, I understand if it isn't necessary.
-v

**Comment by dylanaraps** [comment]
This is definitely something we should look into. I wonder if `git` has some kind of option to `pull` from multiple repositories at once.

**Comment by vypr** [comment]
I found this whilst looking through Stackoverflow, not sure if it'd be applicable.

`find . -type d -depth 1 -exec git --git-dir={}/.git --work-tree=$PWD/{} pull origin master \;`

Explanatory comment here: https://stackoverflow.com/a/12495234/2577858

**Comment by vypr** [comment]
Actually, disregard that last comment, I wasn't thinking correctly.

It seems that the only way is to just do it recursively. There's no built-in support for multiple repos in `git`. You *could* make the repos into submodules of a git repo (that contains all of the repos) and update them all that way through `git submodule update --recursive`, but whether that's substantially different than iteratively going through $KISS_PATH is uncertain. Might be nicer to write at best, but requiring some major changes to $KISS_PATH.

If this path is taken, we'd need to turn $KISS_PATH into a general 'repos' folder that the user can put their repositories in, either by hand or through a function that adds a repo in the cli.

Which, come to think of it, doesn't sound all too bad. `kiss addrepo <link_to_zip/git>` would make repository management all the more convenient and wouldn't be outside the scope of what `kiss` should do.

**Comment by dylanaraps** [comment]
Done. It's always on. I will make this configurable in the future, I need to finalize *how* the package manager will be configured.
